# Nom du workflow
name: Docker Build

# Déclencheur du workflow
on:
  push:
    branches:
      - pipline-attraction

# Configuration des jobs
jobs:
  build:
    # Runner à utiliser
    runs-on: self-hosted

    # Étapes du job
    steps:
      # Étape pour récupérer le code du repository
      - name: Checkout du code
        uses: actions/checkout@v3

      # Étape pour construire l'image Docker
      - name: Construction de l'image Docker
        run: docker build -t chetouiiftikhar/category-docker-image .

      # Éventuellement, une étape pour pousser l'image construite vers un registre Docker
      # - name: Pousser l'image Docker
      #   run: docker push chetouiiftikhar/category-docker-image
