apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-guide
  template:
    metadata:
      labels:
        app: app-guide
    spec:
      containers:
        - name: contdiscoveryy
          image: izdihargh/front-discovery 
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
    